apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: starbucks
  template:
    metadata:
      labels:
        app: starbucks
    spec:
      containers:
      - name: starbucks
        image: ghandgevikas/star-bucks:latest
        ports:
        - containerPort: 3000  # Port your application listens on
