apiVersion: apps/v1
kind: Deployment
metadata:
  name: starbucks-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: startbucks
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: ghandgevikas/hoststar:latest
        ports:
        - containerPort: 3000  # Port your application listens on